import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Eye, FileWarning, ShieldCheck, XCircle } from "lucide-react";
import AdminShell from "../../components/layout/AdminShell";
import api from "../../api/api";
import { EmptyState, SkeletonRows, confirmAction, notify } from "../../components/common/Feedback";

const headers = () => { const token = localStorage.getItem("buddybook_admin_token") || localStorage.getItem("buddybook_token"); return { headers: { Authorization: `Bearer ${token}` } }; };
export default function AdminKyc() {
  const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState(null); const [reason,setReason]=useState("");
  const load=useCallback(()=>{setLoading(true);api.get("/admin/kyc",headers()).then(({data})=>setRows(data?.data||[])).catch(()=>notify("KYC records could not be loaded.","error")).finally(()=>setLoading(false));},[]);
  useEffect(load,[load]);
  const decide=async(status)=>{ if(status==="REJECTED"&&!reason.trim()){notify("Enter a rejection reason.","error");return;} const ok=await confirmAction({title:`${status==="VERIFIED"?"Approve":"Reject"} verification?`,message:selected.fullName,confirmLabel:status==="VERIFIED"?"Approve":"Reject",danger:status==="REJECTED"});if(!ok)return; try{await api.patch(`/admin/kyc/${selected.id}`,{status,reason},headers());notify("KYC decision saved.");setSelected(null);setReason("");load();}catch(e){notify(e.response?.data?.message||"Decision could not be saved.","error");}};
  return <AdminShell eyebrow="Trust operations" title="KYC Approvals" text="Review identity evidence, record decisions and keep a complete approval history.">
    <div className="overflow-hidden rounded-[2rem] border border-black/10 bg-white">{loading?<SkeletonRows count={7}/>:!rows.length?<EmptyState icon={ShieldCheck} title="No KYC submissions" text="New identity submissions will appear here." onAction={load}/>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-black text-xs uppercase tracking-wider text-white"><tr><th className="p-4">Member</th><th>Status</th><th>Documents</th><th>Submitted</th><th>History</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-black/5"><td className="p-4"><div className="flex items-center gap-3"><img src={row.profileImage||row.referenceSelfie||"https://placehold.co/80"} className="h-11 w-11 rounded-full object-cover"/><div><p className="font-black">{row.fullName}</p><p className="text-xs text-black/45">{row.role} · {row.phone}</p></div></div></td><td><span className="rounded-full bg-[#fff1df] px-3 py-1 text-xs font-black">{row.kycStatus}</span></td><td className="text-sm font-bold">{row.kycVerification?.documentType||"KYC"} · {row.kycVerification?.documentNumber||(row.kycVerification?.documentNumberLast4?`•••• ${row.kycVerification.documentNumberLast4}`:row.aadhaarLast4?`•••• ${row.aadhaarLast4}`:"—")}</td><td className="text-sm">{new Date(row.createdAt).toLocaleDateString()}</td><td className="text-sm font-bold">{row.history?.length||0} decisions</td><td><button onClick={()=>setSelected(row)} className="inline-flex items-center gap-2 rounded-full bg-black px-4 py-2 text-xs font-black text-white"><Eye size={15}/>Review</button></td></tr>)}</tbody></table></div>}</div>
    {selected?<div className="fixed inset-0 z-[10000] grid place-items-center bg-black/60 p-5"><div className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-[2rem] bg-white p-7"><div className="flex justify-between"><div><p className="text-xs font-black uppercase text-[#df843f]">Identity review</p><h2 className="text-3xl font-black">{selected.fullName}</h2></div><button onClick={()=>setSelected(null)}><XCircle/></button></div><div className="mt-4 rounded-2xl bg-[#f7f7f5] p-4 text-sm font-bold">Document: {selected.kycVerification?.documentType||"—"} · {selected.kycVerification?.documentNumber||(selected.kycVerification?.documentNumberLast4?`•••• ${selected.kycVerification.documentNumberLast4}`:selected.aadhaarLast4?`•••• ${selected.aadhaarLast4}`:"—")}</div><div className="mt-6 grid gap-5 md:grid-cols-2"><Document title="Reference selfie" src={selected.referenceSelfie||selected.profileImage}/><Document title="Identity document" src={selected.kycVerification?.documentUrl}/></div><div className="mt-6 rounded-2xl bg-[#fffaf3] p-5"><h3 className="font-black">Decision history</h3><div className="mt-3 grid gap-2">{selected.history?.length?selected.history.map(item=><div key={item.id} className="flex justify-between rounded-xl bg-white p-3 text-sm"><b>{item.status}</b><span>{item.reason||"Approved"} · {new Date(item.createdAt).toLocaleString()}</span></div>):<p className="text-sm text-black/45">No previous decisions.</p>}</div></div><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Rejection reason (required when rejecting)" className="mt-5 min-h-24 w-full rounded-2xl border border-black/10 p-4"/><div className="mt-4 flex justify-end gap-3"><button onClick={()=>decide("REJECTED")} className="inline-flex gap-2 rounded-full bg-rose-600 px-5 py-3 font-black text-white"><FileWarning/>Reject</button><button onClick={()=>decide("VERIFIED")} className="inline-flex gap-2 rounded-full bg-emerald-600 px-5 py-3 font-black text-white"><CheckCircle2/>Approve</button></div></div></div>:null}
  </AdminShell>;
}
function Document({title,src}){const pdf=/\.pdf(?:$|\?)/i.test(String(src||""));return <div className="overflow-hidden rounded-2xl border border-black/10 bg-[#f7f7f5]"><p className="p-3 text-sm font-black">{title}</p>{src?(pdf?<iframe src={src} title={title} className="h-72 w-full bg-white"/>:<img src={src} alt={title} className="h-72 w-full object-contain"/>):<div className="grid h-72 place-items-center text-sm font-bold text-black/40">No document uploaded</div>}</div>}
